lugares = ["suiza", "colombia", "singapur", "españa", "usa"]
print("Los lugares a los que deseo ir son:", lugares)
print("Lugares en orden alfabetico:", sorted(lugares))
print("Lista original:", lugares)
print("Lugares en orden alfabetico inverso:", sorted(lugares, reverse=True))
print("Lista original:", lugares)
lugares.reverse()
print("Lista inversa permanentemente:", lugares)
lugares.reverse()
print("Lista restablecida permanentemente:", lugares)
lugares.sort()
print("Lista en orden alfabetico permanente:", lugares)
lugares.sort(reverse=True)
print("Lista en orden alfabetico inverso permanente:", lugares)